%This function calculates the torque generated by the magnetorquer
%This will be in "reality" i.e. the spacecraft will not be modeling this
%torque.

%% INPUTS
%b-field - 3 x 1 vector in inertial frame
%euler_params  - quaternion representation of spacecraft wrt the in
%ID - integer that identifies which magnetorquer is being actuated
%     each magnetorquer is aligned with a body axis 
%     1 - b_x
%     2 - b_y  
%     3 - b_z

%torque - 3 x 1 vector expressed in body frame

function mu = magnetorquer(ID)
%Euler Params need to be eta, eps_1, eps_2, eps_3
magnetorquer_max_dipole = 0.9; %A*m^2
magnetorquer_direction = zeros(3,1);
switch (ID)
    case 1
        magnetorquer_direction = [1;0;0];        
    case 2
        magnetorquer_direction = [0;1;0];   
    case 3
        magnetorquer_direction = [0;0;1];
end

mu = (magnetorquer_max_dipole * magnetorquer_direction);
end
